### ISSUE TITLE
Glass is completly invisible

### ISSUE THREAD

**Issue by oddball250** [F32Organization/Faithful32-1.7.10#454] opened 2015-09-12 16:12 UTC
Glass is invisible and parts of glass plane is missing on the edges

**Comment by steveowashere** [comment] 2015-09-12 16:30
Screenshots? 

Which glass from which mod? Or just vanilla glass?

**Comment by Xen1290** [comment] 2015-09-12 16:58
https://github.com/F32Organization/Faithful32-1.7.10/issues/120

**Comment by oddball250** [comment] 2015-09-12 17:46
i had another quick look and its the small items in the inventory that are missing the glass, eg rainmaker and other glass things, they appear when placed, but the glass plane is missing a couple pixels around the edge of it, Sorry no screen shots though my screenshoot folders broken for somereason


________________________________

**Comment by Evolution0** [comment] 2015-09-17 17:18
Its like this: if its missing in the game but not in the texture itself it isn't the fault of the texture but the way the texture is being processed/displayed.

In this case its probably due to texture filtering of some sort. Nothing that can be done from this end without ruining the textures (thicker lines etc)

So as @Xen1290 pointed out this is a duplicate of a closed issue.

**Closed** 2015-10-10 18:48 UTC
