### ISSUE TITLE
[Ender IO] Pulsating + Ender Crystal textures too similiar.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [F32Organization/Faithful32-1.7.10#321] opened 2015-06-02 07:32 UTC
Same issue as with the capacitor, the ender and pulsating crystals are too similiar in color.

Perhaps it's a good idea to revisit the Faithful ideology in this case. Even though Pulsating and Vibrant alloy have similiar color hue, it might be a good idea to do it different in this texture pack.

**Comment by StefanTT** [comment] 2015-06-03 15:36
Please have a look at https://github.com/F32Organization/Faithful32-1.7.10/pull/322

It's somewhat better with this change. The problem is IMO the pulsating effect on both crystals which has the same effect color.

**Comment by DZCreeper** [comment] 2015-06-07 10:34
Going to close this for now. From what I understand changing the textures further would require a deviation from the normal EnderIO textures. If this is an issue with vanilla EnderIO crystal textures, bring it up with on their Github page and once those are changed, Faithful will be updated to match.

**Closed by DZCreeper** 2015-06-07 10:34 UTC
