### ISSUE TITLE
Optifine connected textures

### ISSUE THREAD

**Issue by MarcusLee1** [F32Organization/Faithful32-1.7.10#120] opened 2015-02-25 19:12 UTC
Hi, I was wondering if it would be possible to show the items in the crafting interface / inventory as some modded glass items are broken / not optimized for Optifine. Would it be possible to fix this issue? It causes quite a few problems for me as I might not notice that glass is required in some crafting recipes. Here's some missing / broken textures from the mods: Edged Glass (Extra Utilities), Thickened Glass (Extra Utilities), Glass Bricks (Extra Utilities), Heart Glass (Extra Utilities), Square Glass (Extra Utilities), Clear Glass (Tinkers' Construct), Glass (Minecraft). Minecraft Version is 1.7.10 (Vanilla and Modded). Is this problem caused by Optifine or is it the texture pack that doesn't have supported textures for the Optifine connected Glass? I currently have to use the default textures for these glass items which I don't like so much. I hope something can be done about this bug. Thanks!

**Comment by Xee1** [comment] 2015-02-25 20:25
Yeah, this is bug is pretty annoying, it comes from assets/minecraft/mcpatcher/ctm ,only the normal glass is affected.  This is a vanilla pack issue, but I don't know the way to fix it. Any idea @DZCreeper ? Other ctm(optifine support) work.

**Comment by MarcusLee1** [comment] 2015-02-26 19:36
I am getting the problem on modded too, can't just be a Vanilla problem

**Comment by Xee1** [comment] 2015-02-26 20:39
Sorry, Bad english, I mean vanilla and modded pack, but the ctm files ( connected textures) are from vanilla pack. This I mean.

**Comment by Evolution0** [comment] 2015-04-21 09:28
I'm going to assume this was resolved or wasn't a problem of the pack to begin with as I can't seem to reproduce it in modded or vanilla (with optifine).

Maybe someone close it?

**Comment by DZCreeper** [comment] 2015-04-21 10:55
Fairly certain its an issue by the Anisotropic Filtering video setting. Going to test a bit tomorrow on my various computers to see if I can narrow it down more.

**Comment by Evolution0** [comment] 2015-04-21 11:40
That does indeed sound plausible and I didn't check either.. trying some things now..

**Comment by Evolution0** [comment] 2015-06-10 00:20
@DZCreeper 
This can most likely be closed, its due to the fine details/transparency in glass textures and mipmapping in optifine. Without mipmapping everything is fine so its no fault of the pack itself.

**Comment by Xen1290** [comment] 2015-09-03 17:08
As @Evolution0 has said, @DZCreeper this can be closed.

**Closed** 2015-09-03 19:24 UTC
